version: '3.0'
services:
  ocserv:
    image: azusa0127/ocserv
    restart: always
    container_name: ocserv
    privileged: true
    hostname: www.example.com
    ports:
      - 8443:443/udp
      - 8443:443
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "5"
    environment:
      - CA_CN=VPN CA
      - CA_ORG=Big Corp
      - CA_DAYS=9999
      - SRV_CN=www.example.com
      - SRV_ORG=My Company
      - SRV_DAYS=9999
